sudo: required
install: true

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=bluestreak/pwa-fe

services:
  - docker

before_script:
  - docker pull $REPO:latest

script:
  - >
    docker build
    -f Dockerfile
    -t $REPO:$COMMIT
    --cache-from $REPO:latest
    .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
